image:
  repository: localhost:5000/scribble
  tag: registry
  pullPolicy: Always

resources:
  requests:
    cpu: 50m
    memory: 32Mi

env:
- name: CHATBASE_DATABASE
  value: "chatroach"
- name: CHATBASE_USER
  value: "chatroach"
- name: CHATBASE_PASSWORD
  value: ""
- name: CHATBASE_HOST
  value: *host
- name: CHATBASE_PORT
  value: "26257"
- name: KAFKA_BROKERS
  value: *kb
- name: KAFKA_POLL_TIMEOUT
  value: "1s"
- name: SCRIBBLE_CHUNK_SIZE
  value: "32"
- name: SCRIBBLE_BATCH_SIZE
  value: "32"
- name: SCRIBBLE_ERROR_HANDLERS
  value: ""

sinks:
  - destination: "states"
    replicaCount: 1
    env:
    - name: KAFKA_TOPIC
      value: *statetopic
    - name: KAFKA_GROUP
      value: "scribble-states"
    - name: SCRIBBLE_CHUNK_SIZE
      value: "1"
    - name: SCRIBBLE_BATCH_SIZE
      value: "16"
    - name: SCRIBBLE_ERROR_HANDLERS
      value: "foreignkey"

  - destination: "responses"
    replicaCount: 1
    env:
    - name: KAFKA_TOPIC
      value: *responsetopic
    - name: KAFKA_GROUP
      value: "scribble-responses"

  - destination: "messages"
    replicaCount: 1
    env:
    - name: KAFKA_TOPIC
      value: *topic
    - name: KAFKA_GROUP
      value: "scribble-messages"
