image:
  repository: localhost:5000/scribble
  tag: registry
  pullPolicy: Always

resources:
  requests:
    cpu: 50m
    memory: 32Mi

env:
- name: CHATBASE_DATABASE
  value: "chatroach"
- name: CHATBASE_USER
  value: "chatroach"
- name: CHATBASE_PASSWORD
  value: ""
- name: CHATBASE_HOST
  value: "gbv-cockroachdb-public"
- name: CHATBASE_PORT
  value: "26257"
- name: KAFKA_BROKERS
  value: "gbv-kafka:9092"
- name: KAFKA_POLL_TIMEOUT
  value: "20s"
- name: SCRIBBLE_CHUNK_SIZE
  value: "2"
- name: SCRIBBLE_BATCH_SIZE
  value: "4"

sinks:
  - destination: "states"
    replicaCount: 1
    env: 
    - name: KAFKA_TOPIC
      value: "vlab-state"
    - name: KAFKA_GROUP
      value: "scribble-states"
  - destination: "responses"
    replicaCount: 1
    env:
    - name: KAFKA_TOPIC
      value: "vlab-response"
    - name: KAFKA_GROUP
      value: "scribble-responses"
  - destination: "messages"
    replicaCount: 1
    env:
    - name: KAFKA_TOPIC
      value: "chat-events"
    - name: KAFKA_GROUP
      value: "scribble-messages"
