image:
  repository: vlabresearch/scribble
  tag: 0.0.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 32Mi

env:
- name: CHATBASE_DATABASE
  value: "chatroach"
- name: CHATBASE_USER
  value: "chatroach"
- name: CHATBASE_PASSWORD
  value: ""
- name: CHATBASE_HOST
  value: "gbv-cockroachdb-public"
- name: CHATBASE_PORT
  value: "26257"
- name: KAFKA_BROKERS
  value: "gbv-kafka:9092"
- name: KAFKA_POLL_TIMEOUT
  value: "30m"
- name: KAFKA_GROUP
  value: "scribble"
- name: SCRIBBLE_CHUNK_SIZE
  value: "12"
- name: SCRIBBLE_BATCH_SIZE
  value: "12"

sinks:
  - destination: "states"
    replicaCount: 1
    env: 
    - name: KAFKA_TOPIC
      value: "vlab-state"
  - destination: "responses"
    replicaCount: 1
    env:
    - name: KAFKA_TOPIC
      value: "vlab-response"
  - destination: "messages"
    replicaCount: 1
    env:
    - name: KAFKA_TOPIC
      value: "chat-events"
