{{- range .Values.sinks }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scribble.fullname" $ }}-{{ .destination }}
  labels:
    {{- include "scribble.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "scribble.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scribble.selectorLabels" $ | nindent 8 }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            {{- toYaml $.Values.env | nindent 12 }}
            - name: SCRIBBLE_DESTINATION
              value: .destination
            {{- toYaml .env | nindent 12 }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
    {{- end }}
---
{{- end }}
