on: 
  push:
    branches:
      - dev
name: deploy-dev
jobs:
  deploy:
    name: build-deploy-dev
    runs-on: self-hosted
    steps:
    - uses: actions/first-interaction@v1.0.0
      with:
        ref: cicd
    - name: build-deploy-2
      run: |
        ~/build-deploy-2